apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deploy-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: deploy-1
        image: dockerghana1/deploy:v1
        ports:
        - containerPort: 80
