apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 80    
  type: ClusterIP 
